spring:
  application:
    name: spring-consumer
    
server:
  port: 1991

  
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
       defaultZone: http://localhost:1992/eureka
    instance:
       hostname: localhost